import type { Config } from "tailwindcss";

const config: Config = {
    darkMode: "class",
    content: [
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "secondary-fixed-dim": "#4cd7f6",
                "background": "#051424",
                "on-background": "#d4e4fa",
                "secondary": "#4cd7f6",
                "inverse-primary": "#842bd2",
                "surface": "#051424",
                "tertiary": "#fbabff",
                "outline-variant": "#4d4354",
                "surface-container-highest": "#273647",
                "surface-container-low": "#0d1c2d",
                "on-secondary-container": "#00424e",
                "surface-dim": "#051424",
                "on-surface": "#d4e4fa",
                "primary-container": "#b76dff",
                "secondary-fixed": "#acedff",
                "on-surface-variant": "#cfc2d6",
                "on-primary-container": "#400071",
                "on-error-container": "#ffdad6",
                "inverse-on-surface": "#233143",
                "on-error": "#690005",
                "inverse-surface": "#d4e4fa",
                "surface-tint": "#ddb7ff",
                "error-container": "#93000a",
                "on-primary-fixed-variant": "#6900b3",
                "secondary-container": "#03b5d3",
                "primary-fixed": "#f0dbff",
                "on-tertiary-fixed-variant": "#7c008e",
                "on-secondary": "#003640",
                "on-primary": "#490080",
                "outline": "#988d9f",
                "primary-fixed-dim": "#ddb7ff",
                "error": "#ffb4ab",
                "on-tertiary-fixed": "#36003e",
                "on-tertiary": "#580065",
                "on-primary-fixed": "#2c0051",
                "tertiary-fixed-dim": "#fbabff",
                "surface-bright": "#2c3a4c",
                "primary": "#ddb7ff",
                "tertiary-container": "#e14ef6",
                "surface-variant": "#273647",
                "tertiary-fixed": "#ffd6fd",
                "on-secondary-fixed-variant": "#004e5c",
                "surface-container-high": "#1c2b3c",
                "on-secondary-fixed": "#001f26",
                "on-tertiary-container": "#4d0059",
                "surface-container-lowest": "#010f1f",
                "surface-container": "#122131",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                "stack-md": "24px",
                "stack-sm": "8px",
                "margin-desktop": "48px",
                "gutter": "24px",
                "margin-mobile": "16px",
                "stack-lg": "64px",
                "unit": "4px",
                "container-max": "1280px",
            },
            fontFamily: {
                "body-lg": ["Plus Jakarta Sans", "sans-serif"],
                "headline-md": ["Space Grotesk", "sans-serif"],
                "display-md": ["Space Grotesk", "sans-serif"],
                "display-lg": ["Space Grotesk", "sans-serif"],
                "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
                "body-md": ["Plus Jakarta Sans", "sans-serif"],
                "headline-lg": ["Space Grotesk", "sans-serif"],
                "label-sm": ["Geist", "sans-serif"],
                "display-lg-mobile": ["Space Grotesk", "sans-serif"],
            },
            fontSize: {
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
                "display-md": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
                "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
                "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
                "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "500" }],
                "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
            },
        },
    },
    plugins: [],
};

export default config;
